name: 'debby_demo'

config-version: 2
version: '0.1'

profile: 'debby-demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

query-comment:
  comment: "{{ debby.query_comment(node) }}"
  append: true

tests:
  store_failures: true
  limit: 10

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  debby_demo:
    materialized: table
    staging:
      materialized: view
