debby-demo:

  target: tmp
  outputs:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 8
      user: "{{ env_var('SNOWSQL_USER') }}"
      password: "{{ env_var('SNOWSQL_PWD') }}"
      account: "{{ env_var('SNOWSQL_ACCOUNT') }}"
      database: "{{ env_var('SNOWSQL_DATABASE', 'demo') }}"
      schema: "{{ env_var('SNOWSQL_SCHEMA', 'dev') }}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE', 'demo') }}"
      role: "{{ env_var('SNOWSQL_ROLE', 'demo_transformer') }}"

    prod:
      type: snowflake
      threads: 8
      user: "{{ env_var('SNOWSQL_USER') }}"
      password: "{{ env_var('SNOWSQL_PWD') }}"
      account: "{{ env_var('SNOWSQL_ACCOUNT') }}"
      database: "{{ env_var('SNOWSQL_DATABASE', 'demo') }}"
      schema: "{{ env_var('SNOWSQL_SCHEMA', 'prod') }}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE', 'demo') }}"
      role: "{{ env_var('SNOWSQL_ROLE', 'demo_transformer_prod') }}"
